{% set version = "8.10.1" %}

package:
  name: curl_split_recipe
  version: {{ version }}

source:
  url: http://curl.haxx.se/download/curl-{{ version }}.tar.bz2
  sha256: 3763cd97aae41dcf41950d23e87ae23b2edb2ce3a5b0cf678af058c391b6ae31

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libtool        # [unix]
    - make           # [unix]
    # perl is required to run the tests on UNIX.
    - perl           # [unix]
    - pkg-config     # [unix]
  host:
    - zstd           # [unix]
    - libnghttp2     # [unix]
    - openssl        # [unix]
    - brotli
    - krb5
    - libssh2
    - zlib

outputs:
  - name: libcurl
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
      host:
        - libnghttp2  # [unix]
        - openssl     # [unix]
        - zstd        # [unix]
        - brotli
        - krb5
        - libssh2
        - zlib
      run:
        - libnghttp2  # [unix]
        - libbrotlidec
        - libssh2
    build:
      run_exports:
        - {{ pin_subpackage('libcurl') }}
    files:
      - include/curl             # [unix]
      - lib/libcurl.so*          # [linux]
      - lib/libcurl*.dylib       # [osx]
      - lib/pkgconfig/libcurl*   # [unix]
      - bin/curl-config          # [unix]
      - Library/bin/libcurl.dll  # [win]
      - Library/include/curl     # [win]
      - Library/lib/libcurl.lib  # [win]
      - Library/lib/libcurl.exp  # [win]
    test:
      commands:
        - curl-config --features       # [unix]
        - curl-config --protocols      # [unix]
        - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}  # [unix]
        - test ! -f ${PREFIX}/lib/libcurl.a          # [unix]
        - if exist %LIBRARY_BIN%\curl.exe exit 1     # [win]
        - if exist %LIBRARY_LIB%\libcurl_a.lib exit 1     # [win]
        - if not exist %LIBRARY_BIN%\libcurl.dll exit 1   # [win]
        - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)                             # [unix]
        - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi           # [unix]
        - if ! echo $CURL_SSL_BACKENDS | grep -q "Secure Transport"; then exit 1; fi  # [osx]


  - name: libcurl-static
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
      host:
        - {{ pin_subpackage('libcurl', exact=True) }}
        - openssl  # [unix]
        - zstd     # [unix]
        - brotli
        - krb5
        - libssh2
        - zlib
      run:
        - {{ pin_subpackage('libcurl', exact=True) }}
        - libbrotlidec
    files:
      - lib/libcurl.a*             # [unix]
      - Library/lib/libcurl_a.lib  # [win]
    test:
      commands:
        - test -f $PREFIX/lib/libcurl.a                    # [unix]
        - if not exist %LIBRARY_LIB%\libcurl_a.lib exit 1  # [win]

  - name: curl
    files:
      - bin/curl               # [unix]
      - Library/bin/curl.exe*  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
      host:
        - {{ pin_subpackage('libcurl', exact=True) }}
        # OpenSSL is needed here to prevent conda-build from getting confused while
        # both OpenSSL 1.1.1 and 3.0.0 and being supported
        - openssl  # [unix]
        - zstd     # [unix]
        - krb5
        - libssh2
        - zlib
      run:
        - {{ pin_subpackage('libcurl', exact=True) }}
        - libbrotlidec
        - libssh2
    test:
      commands:
        - curl --version
        # curl help commands on Windows have non-zero status codes.  Need other test.
        - curl --help
        # Try downloading something from https to make sure the certs are used correctly.
        - curl https://raw.githubusercontent.com/conda-forge/curl-feedstock/master/LICENSE.txt
        - if not exist %LIBRARY_BIN%\curl.exe exit 1  # [win]

about:
  home: http://curl.haxx.se/
  license: curl
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax

  description: |
    Curl is an open source command line tool and library for transferring data
    with URL syntax. It is used in command lines or scripts to transfer data.
  doc_url: https://curl.haxx.se/docs/
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs

extra:
  recipe-maintainers:
    - msarahan
    - jakirkham
    - ocefpaf
    - mingwandroid
    - xylar
