{% set version = "7.52.1" %}

package:
  name: curl
  version: {{ version }}

source:
  fn: curl-{{ version }}.tar.bz2
  url: http://curl.haxx.se/download/curl-{{ version }}.tar.bz2
  sha256: d16185a767cb2c1ba3d5b9096ec54e5ec198b213f45864a38b3bda4bbf87389b

build:
  number: 0
  detect_binary_files_with_prefix: true
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]

requirements:
  build:
    # for feature activation
    - vc  9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

    # perl is required to run the tests on UNIX.
    - perl             # [unix]
    - pkg-config       # [unix]
    - openssl 1.0.*    # [unix]
    - zlib 1.2.*
  run:
    # for feature activation
    - vc  9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - openssl 1.0.*    # [unix]
    - zlib 1.2.*

test:

  commands:
    # curl help commands on Windows have non-zero status codes.  Need other test.
    - curl --help
    - curl-config --features       # [not win]
    - curl-config --protocols      # [not win]

    # Try downloading something from https to make sure the certs are used correctly.
    - curl https://raw.githubusercontent.com/conda-forge/curl-feedstock/master/LICENSE

about:
  home: http://curl.haxx.se/
  license: MIT/X derivate (http://curl.haxx.se/docs/copyright.html)
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax

extra:
  recipe-maintainers:
    - msarahan
    - jakirkham
    - ocefpaf
