travis:
  secure:
    BINSTAR_TOKEN: NPdRU71QUWC4em/nTn8P0KaAjO0fBWsVKyxtjt0kHfzvXAgPywmz+qT5gBki5lBnQZlY9HFe2Nh1BkuZzm7tVhk3B/Y0t8ntv3OJDck5tQMbF+bE4wsC/BCj28RWjHpnRA7eUyMbH23pd39NjVks26pjVHOR4x4DrejLQT3ThHmPwC7EkGHbnf+bG7hbZhEcyBZvotAs0en7cs9Cdsp+So1SJMZ+orqtR1K4UxeNJ2RzakL8OTeA8uHvrOha19PCfFHEbgXZpzHvJ7crFEuPpd7iZ+7Xgdey9QRP6dX4UI9zVF7Hut08dyoVL2JFu2nmhCjX3JD4iz3cRrAVm/ZLp6mCgJjUtfFfPtZPRnGkCJpYRpjhiYL8OkwmgD+rQKrtSl8fjI3FADIf1NRZtAI4oSGWq4j04buNomAf7i0fErnYDVR2kEo3D9dubxQM/QXyU8TGmj+23Uogm4mQQ4JAi4ARhfR2wqSPSi7QrY6zpJMZi2HLDy+q2YvG5Xzd7EB0nc50mEz/Kzu65hSQijV1hBd/tktPfCC12q7d4uEtHunv9QY72BW4vVim0JLVw+P+WidHkxee+FcBeuVlrsDGHQS9SHgleHqgZbEB5XD6Aw4rdGl+hvOSWZOZJ4w0KqZpMXpQggmOBfFUERGzm9SE+iDGHoXyxr8A5JN2sF3gLh4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
