appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: THO9KgiIivBhuZkvYghQeq/EeiBgh3u9Se2Qc9uKWy2DjO+THN4ILFefpigOd7o9qNLtXEQ6OmtAEuxCSC0GRoZxw4dyLlIo6+AIf1zCJGtyg1/5NWxQ2hkdMJfvsyhLTVN61ISGyJc6JH5QJRkh46g1Ak3WO25liAXqvKNUMvffq7OA93tVyqDZAqpVw3rmFg8miqpMtr9FmYjm//EnV163NZYCkY2b6MTBBFB9mkMFn4P7Ymve9ttb02U0LYPHXeQZ6Z5fXlgIt9dxNuaV8yE9NtlSeqLmi4VNUY6+7+kgp77SFV9m6X/vVmOp/ez3SPEN95oru0pFLilh0SE+QIC+htxfmcDcOEP1Fd1FlOG4hlFSCDQcf0yYUlLr7h2QrsSY2+sIZHLkOH3XLf54siEC7O3ZEujpBcIkCr5DpPLjvoAyJ4bCtsqfONqiOjYzE2Sh1ISp3qH4dcCSVdunIf0TgsXmwKh/eP2sqSGU+GrlHWgi/vV7qZN/Z15DP5Tf1pl0Ksz0LsfLtP4Kh+S7L8q3bSux6vR8TYbuw+gOyJ4HuIEKgeMgTddMxmpqUOPZnxgVg4+WgIdRobx2ez/KXNVjKybEhBVH8mok+h12Vzbh15p954jtgtMl6Nzfg6/uaUuJP/5B4c84Yh+2JpjFqz8veXOlMRzZLT1eBcfU2vU=}
